### ISSUE TITLE
Compass Sprites

### ISSUE THREAD

**Issue by Romiko** [jekyll/jekyll-assets#110]
Hi,

I am using Compass Sprites.
_assets\images\source\1.png
_assets\images\source\2.png
_assets\images\source\3.png

When I have this in my scss

//Sprites
@import "source/*.png";

I get an error with Jekkyl build.

Liquid exception: No files were found in the load path matching "source/*.png". You current load paths are ./images ....

How can I get Compass Sprite support work to work correctly?

**Comment by ixti** [comment]
I need a prepared sandbox where I can play with (I don't have any compass-related projects and going remove all vendors support out of jekyll/assets plugin in future - will better extract them out rather than will hack around with them). Most likely there's some adoptions of `compass-rails` will be needed.

**Comment by ixti** [comment]
Wow! I just realized that I have compass-based project... My own blog is using jekyll-assets with compas o_O Completely forgot about that. But I never used sprites so far... So a sandbox will really help me a lot.

**Comment by envygeeks** [comment]
What exactly are compass sprites and what benefit do they provide over Sprockets?

**Comment by envygeeks** [comment]
This issue is being closed, there has been no response so I'm to assume this issue is non-important.
