### ISSUE TITLE
Stylus support.

### ISSUE THREAD

**Issue by Fresheyeball** [jekyll/jekyll-assets#126]
It would be hot. So hot.

**Comment by BattleBrisket** [comment]
:+1:

**Comment by BattleBrisket** [comment]
What I find odd is that adding the [`ruby stylus` gem](https://github.com/lucasmazza/ruby-stylus) does not get picked up by `jekyll-assets`'s use of `sprockets`, even though that should be everything that's necessary (according to my reading of the `jekyll-assets` docs anyway).

**Comment by ixti** [comment]
Unfortunately it won't be auto-picked up. Although I try to keep `jekyll-assets` as close to rails assets experience as possible, jekyll is not rails after all ;))

I have a plan how to cleanup an improve assets init, so that it will become possible to inject engines like Stylus into jekyll-assets pretty easily without heavy monkey-patching.

Right now you can achieve that with following (exampe will work in ruby 2.1+):

``` ruby
module Jekyll
  module AssetsPlugin
    module EnvironmentWithStylus
      def initialize(*args)
        super(*args)
        Stylus.setup self
      end

      Environment.send :prepend, self
    end
  end
end
```

**Comment by BattleBrisket** [comment]
> jekyll is not rails after all ;)

Totally agreed, which is why I made sure to specify the Sprockets dependency, and not Rails.

Here's a complete example for enabling Stylus with `jekyll-assets`

```ruby
# Gemfile
gem "jekyll-assets"
gem "stylus"

# _plugins/jekyll_assets_add_stylus.rb
require 'stylus'
require 'sprockets'
require 'stylus/sprockets'

module Jekyll
  module AssetsPlugin
    module EnvironmentWithStylus
      def initialize(*args)
        super(*args)
        Stylus.setup self
      end

      Environment.send :prepend, self
    end
  end
end
```

**Comment by Fresheyeball** [comment]
what if I need to pass arguments to `Stylus.compile` like 

```
Stylus.compile content, { 'include css' => true }
```
?

**Comment by envygeeks** [comment]
I feel the need to iterate why this was reverted and reopened, it's because the stylus plugin for Sprockets has design problems that cause memory issues on JRuby and because Jekyll now supports JRuby when this blocked our JRuby support here to stay in parity it was removed, I will be looking into either patching their source to fix the problem or creating my own stylus addon in 2.1 so this is being skipped for the initial 2.0 alpha release.

**Comment by untra** [comment]
I hate to necropost, but is there a new approach to stylus compilation with Jekyll? The brief code snippet @BattleBrisket posted works for jekyll 2.5.3, but it doesn't seem to cooperate with jekyll 3.0 beta 9.

**Comment by envygeeks** [comment]
We do not support plugins in 2.0.0 alpha, we now use Hooks the same as Jekyll 3.0, so if you are on the beta you need attach yourself to a hook rather than create a plugin.

**Comment by envygeeks** [comment]
At this time, we have no plans to offer stylus.  Sorry.

**Comment by simonhaenisch** [comment]
@envygeeks would you mind sharing a snippet for how to have a stylus hook? I'm new to this eco system.
