### ISSUE TITLE
Compass Support

### ISSUE THREAD

**Issue by hijonathan** [jekyll/jekyll-assets#170]
Seems like this got dropped in v1. If you have docs on how to implement this, I'm happy to take a crack at it.

**Comment by envygeeks** [comment]
Unfortunately v1 is feature locked and no more features will be added ever because we are moving and working on v2 but we do plan on adding support to v2 which will be released in tandem with Jekyll 3.0.

**Comment by hijonathan** [comment]
Cool. Do you need help adding Compass support to `2.0`? I'm on Jekyll `3.0` and would love to keep Compass support from this gem.

**Comment by envygeeks** [comment]
Pull requests are always welcome, but I never require them for features because for me most of the time it's a matter of time, but if you can tell me what happens when you try to use compass I can probably implement it with little effort but I assume the major problem is probably that we simply just don't detect it and add it's paths or require it but since we use Sprockets 3 it should in theory be supported out of the box on v2.

**Comment by hijonathan** [comment]
Thanks for the offer to help. I get this error when I load a page that uses a compass import in a sass file:

`Liquid error: File to import not found or unreadable: compass/css3/box-shadow. Load path: /path/to/repo`

The file it's throwing an error on is located in `/_assets/stylesheets/style.sass` and has `@import compass/css3/box-shadow` as the first line in the file.

**Comment by hijonathan** [comment]
I think you're right about it just not being in the path.

**Comment by envygeeks** [comment]
Ah okay yeah that's just us not including it's paths, I'll go look at the repo in a few minutes and see what I can work out for v2 and get it up today so you can play with it, but just note that the syntax for our tags has changed in v2 and we don't yet have filters (I plan on adding the filters back this week after my build servers are reopened -- we are currently rebuilding thousands of Docker instances on our clusters for new images)

**Comment by hijonathan** [comment]
You rock! FWIW I don't actually use filters, so just having tags would be huge!

**Comment by hijonathan** [comment]
Any luck?

**Comment by envygeeks** [comment]
@hijonathan sorry I haven't had time to look at it, I'll try to make time today.

**Comment by envygeeks** [comment]
Hulk: envygeeks/jekyll-assets:backlog++ : Make Important

This issue has been neglected, it's been put into the backlog as an important issue that will get fixed in the next week as I pushed out more beta's to prepare for the final push with Jekyll 3.  I apologize for not getting it done sooner but I've had a huge backlog this summer.
