### ISSUE TITLE
Custom Output Folder For Images

### ISSUE THREAD

**Issue by igolden** [jekyll/jekyll-assets#195]
Hi, loving the jekyll-assets gem! Really makes the workflow 'railsy'

I'm trying to setup a custom output folder for my images, wondering if that's possible?

Right now all my images are output to /assets/\* , but I'd like them to be in the typical static site output of img/

I can accomplish this by putting my images outside of the assets folder, but I don't really like that solution. Just wondering if I could specify this within config somehow.

Thanks in Advance!

**Comment by envygeeks** [comment]
Right now it's not possible and if I'm honest I don't know how easy it would be because I've never considered overriding the Ruby convention.  I know it's possible and I can see in my head where and how to do it, but I've never done it so I cannot feasibly gauge for you if this will land anytime soon.

I'll look into it on Monday when I'm preparing the 2.0 final release and update you one when I can do this in the order of backlog items that need to be done for `jekyll-assets`

**Comment by igolden** [comment]
Want to give me some insight on your thoughts? I'd be interested in possibly working on this during the weekends, because it would be valuable 10x over for me. I use jekyll-assets to build 5-10+ static sites a month, and right now I have this lone 'img' folder sitting outside my assets folder. Creating this workflow is the missing piece of our setup.

I'd be happy to submit a PR if it's up my alley. Just point me in the direction to we're on the same page. 

Thanks.

**Comment by envygeeks** [comment]
1. It should append to the prefix path and not replace it.  Which means you will need to "" the prefix path, because without this we will break behavior which will force me to put this off until 3.0 which will wait until Sprockets 4.0 is out.  There is no date for Sprockets 4 so there is no date for jekyll-assets 3.0, so to get around that you'll need to just force people to do "" and add the behavior you want on top of that.

2. You'll need to modify https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/env.rb#L129-L137 and split it off into two methods, pass it the asset, detect the configuration option, pass it the asset, detect the type, and set the folder.  That's the easy part.  That's already a somewhat complex method, so it really needs to be split off it more logic is coming.

3. You'll need to hit upstream and create a patch file or ask them to accept a patch that modifies their helpers to detect and use our helper dynamically, rather than statically.  I don't assume it accepts a proc right now: https://github.com/petebrowne/sprockets-helpers

---

There is an alternate to 3 you could just create helpers but that's a lot of work, that is something I planned to do in version 3.0 of Jekyll assets since we don't use half the stuff our upstream provides and we don't need half that stuff.  I don't expect you to do that.

---

I am fine with a monkey patch for our upstream, we provide a patch folder in the source explicitly so we can track our patches and remove them when the time comes (if it comes, some of those aren't meant to be removed but a few are place holders.) 

---

The complexity here isn't the work, it's the moving parts that need to be adjusted.

**Comment by igolden** [comment]
This will take me some significant time and testing, but I'm not opposed to working on a patch. I appreciate the detailed response.

In the meantime, how can I include ALL of the images in the assets folder, not just the ones I call via an image tag? I feel like i've just overlooked this part of the process.

Thanks again.

**Comment by envygeeks** [comment]
There is an example of doing that right in the README: https://github.com/jekyll/jekyll-assets#configuration

**Comment by envygeeks** [comment]
This is shifting to 2.2.0 because 2.0.* ended up being 2.1.0 because of a necessary API change.

**Comment by envygeeks** [comment]
This has been supported in Jekyll assets for quite sometime via the `prefix` configuration.
