### ISSUE TITLE
Can't get "require 'jekyll-assets/bootstrap'" to work: `require': cannot load such file -- [132/479]sets/bootstrap (LoadError)

### ISSUE THREAD

**Issue by karlmdavis** [jekyll/jekyll-assets#196]
Here's the `_plugins/etc.rb` file that's giving me this error when running `bundle exec jekyll serve`:

```
require 'jekyll-assets'
require 'jekyll-assets/bootstrap'
```

And here's my `Gemfile`:

```
source 'https://rubygems.org'

##
# Install all these gems by running `bundle install`
##

# The static site generator used to compile this whole project.
gem 'jekyll'

# Provides an asset pipeline for Jekyll, which is used to build Bootstrap, etc.
gem 'jekyll-assets',  '>=2.0.0.pre.beta4'

# Bring in the SASS fork of Bootstrap, which jekyll-assets has builtin support for.
gem 'bootstrap-sass'
```

**Comment by karlmdavis** [comment]
Replacing `require 'jekyll-assets/bootstrap'` with `require 'bootstrap-sass'` seems to be a viable workaround, but it's definitely not what's documented.

**Comment by envygeeks** [comment]
Except I don't say anywhere in the documentation for Jekyll Assets 2.0 to require "jekyll-assets/bootstrap" and assuming that things will be the same between major versions is a fallible approach to any software.

Removing the `require jekyll-assets/bootstrap` is NOT the work around... it is now you get bootstrap support. Period.  There are no other ways, we do not have files you require, we require everything on your behalf.  The documentation for 2.0 clearly states to just add the gem to the Gemfile and we will do the rest.

I'm sorry but this is not a bug.

**Comment by karlmdavis** [comment]
Apologies if I'm missing something, but I see this in the documentation at <http://ixti.net/jekyll-assets/>:

![screenshot from 2015-11-08 13 10 03](https://cloud.githubusercontent.com/assets/59200/11021755/27c61372-861a-11e5-9dbd-938a4a4d805d.png)

Maybe I'm using the wrong version, or looking at the wrong set of documentation?

**Comment by envygeeks** [comment]
We've never updated that site because it's the personal domain of @ixti and most people read the README.md first for beta versions: https://github.com/jekyll/jekyll-assets#addons.

If you like you can file a more direct ticket for that and I'll ping him again asking him to work with me on separating it so we can maintain them differently without messing with his domain (such as forwarding that specific URL to jekyllrb.org if @parkr is okay with it) and maintaining it there since it's now under our umbrella with @ixti and I maintaining it together.

Most of the documentation on that site does not apply to 2.0.  Only the surface of it does as we've tried to maintain a simple parity but have diverged in some other spots.

**Comment by ixti** [comment]
And I'm not sure HOW to remove that old site in fact.. because it was a gh-pages stuff generated when gem was developed as `ixti/jekyll-assets`...
