### ISSUE TITLE
Image tags compiling on index page, not on post pages

### ISSUE THREAD

**Issue by charliesneath** [jekyll/jekyll-assets#200]
I am using `{% image hero-image.jpg %}` in a post.

The tag correctly converts to `<img src="/assets/hero-image.jpg"/>` when the post is rendered on the site's index page (which loops through and displays all posts), but the tag does not render when clicking through to the post.

How can I fix this?

**Comment by envygeeks** [comment]
Define: 'not being processed' because so far from my deductions this is an upstream problem because we process through Jekyll via Liquid.  Which means that if Jekyll doesn't tell liquid to process the post, then nothing will happen.  Can you provide replication steps as a repo I can pull to test it?

/cc @jekyll/core

**Comment by charliesneath** [comment]
@envygeeks Got it — the upstream template was using `{{ page.content }}` instead of `{{ content }}`, which meant it wasn't processing the Liquid variables when rendering.

Thanks for the help.
