### ISSUE TITLE
Support more fractional values / booleans in the magick proxy

### ISSUE THREAD

**Issue by mshick** [jekyll/jekyll-assets#201]
I'd love to see freeform fractional values supported, similar to "magick:half" e.g. "magick:2/3", "magick:x/y", "magick:0.25", etc... 

Or maybe this should live under the resize proxy, with the logic branch determined by the symbol, e.g. "magick:resize:x/y"

FYI, my use-case is making srcsets that can responsively serve fractionally-sized large images for mobile, small screens, etc.

Also, forgive me if I'm being dense, but what is the use-case for the 2x and 4x booleans? Using imagemagick to up-res an image, embedded in an img tag, doesn't make a ton of sense to me since it seems like it will only ever waste CPU and bandwidth. Wouldn't someone only ever be interested in down-res'ing an image on the server?

**Comment by envygeeks** [comment]
Your use case is not his or her usecase and asking for that usecase removal while arguing for a new usecase is a tad bit ironic.

Trying to compare them is not such a good thing.  It was there originally so somebody asked for it... well the 2x was, the 4x was added because sometimes you need it, which means somebody had the usecase and it will stay because it doesn't affect you.  I'm not trying to be mean but removing features that are negligible is not good policy.  The CPU time is literally negligible and a users bandwidth is not my problem if they want it and use it.

**Comment by mshick** [comment]
It was a question, not a request to remove anything.

**Comment by envygeeks** [comment]
We should be able to facilitate the fractional sizing, but again this will happen in 2.1 if I can fit it in otherwise 2.2 because so far this week my backlog has started filling up again because we have a ton of tools being released for Christmas to make things easy for Docker users.

The change itself is actually easy to implement because our proxies are designed to add features like this swiftly it's just a matter of being able to get to it, I might end up doing it before the 2.0 release when I dedicate time to it.

**Comment by envygeeks** [comment]
I'm going to ask that you list out the common fractional sizes you want, we cannot do dynamic fractional sizing as our proxies as it stand require a known value and the API is stable so that will have to wait if you wish for dynamic sizes... wait in that I can add it in a minor point but I'll need to carefully design it as to not break our current API.

**Comment by mshick** [comment]
Yeah, it looked like that was the case based on the code. Thanks for taking it into consideration.

Dynamic values were more to create broadly useful functionality and not lock people into my use-cases, and not clutter up the api with hyphenated English. :)

I often use: 
* quarter
* third
* half (exists) 
* two-thirds
* three-quarters

Most common for a srcset would be stepping values down from a very high-res source (retina, desktop).

**Comment by envygeeks** [comment]
Fixed with: https://github.com/jekyll/jekyll-assets/commit/48f50f12c53536023187f139cb354cb683f8230d

**Comment by mshick** [comment]
Brilliant. Much appreciated. 

One further concern, which I'm curious how you'd approach, is the need for information about either the source image or the downrezzed derivatives. 

Say, for instance, I only want to downrez images that are above a certain size, or I want to calculate breakpoints for srcsets (yes, that again) how might I get that info programmatically? Not asking you to be my search engine, I've looked around and it's not clear to me what tools Jekyll users are using for this.

**Comment by envygeeks** [comment]
There is no way because nothing AFAIW exposes an API like that but if you file a ticket within a few hours (like a few hours before 1800GMT-6) I can add a tag that can expose some basic image information for you through a drop.

**Comment by mshick** [comment]
Cool, will do. Curious to see your implementation too.
