### ISSUE TITLE
Set relative URL?

### ISSUE THREAD

**Issue by halfnibble** [jekyll/jekyll-assets#203]
Is there a way to set the `link` and `script` tags to use relative URLs?

I've tried setting `prefix: "assets"` in _config.yml, but that does nothing (the generated HTML still references `/assets/...` instead of `assets/...`). It'd be nice to have a configuration attribute for using relative URLs.

**Comment by envygeeks** [comment]
For what purpose?

**Comment by fcalderan** [comment]
I had to do the same and I simply inserted a dot ```.``` in front of the ```href/src``` attributes, e.g.:

```<link rel="stylesheet" href=".{{ 'css/common' | asset_path }}" />```

or

```<script src=".{{ 'js/main.js' | asset_path }}"></script>```


-f.

**Comment by envygeeks** [comment]
For what purpose?

**Comment by halfnibble** [comment]
My use case may be unusual, but I have a jekyll site as part of a larger site. There are reverse proxies forwarding different URLs to the different site components.

So my jekyll root directly may actually be "/business/home/" and when a `<script>` tags loads `/assets/...` it is actually being proxied to a different site component. I could set the site URL maybe, but the proxies are subject to change. Therefore, everything in the site just uses relative URLs.

**Comment by envygeeks** [comment]
There is no need for any relative URL stuff in that instance, use Jekyll's base URL option, we will pick it up and use it automatically on master (I don't remember if I've pushed it out as a beta yet, probably have.)

**Comment by halfnibble** [comment]
Ok thanks! I'll pull master.

Do you think I can set my Jekyll base URL to just `""`? Again, my use case may be unusual, but the reverse proxies are subject to change, and I'd rather not rebuild static site components with a new base URL every time they do. 

Perhaps that's something I'll find in Jekyll's documentation...

**Comment by envygeeks** [comment]
No, because we already do that for you, which is probably why you end up with a "/" at the beginning.  The purpose of baseurl is to solve your problem.  If you host Jekyll at /my-path then set the baseurl to `/my-path` and Jekyll will use `/my-path` in the url everywhere and we will also use that path through Jekyll.  See: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/ for more information since I'm too lazy to dig through core documentation to find the other documentation but that has more clarity anyways.

**Comment by halfnibble** [comment]
Ok. Thanks for the info.

I'll just make a note to change baseurl and rebuild whenever a reverse proxy is changed.

**Comment by envygeeks** [comment]
I'm gonna leave this open because even though I don't want to solve the relative path problem, it is a bug  that I noticed, in that I can actually accidentally create a double "//" if people set the baseurl wrong.  I need to fix that problem which will actually fix your problem unintentionally so we'll both be pleased.

**Comment by halfnibble** [comment]
Sounds great. ;-)
