### ISSUE TITLE
Version 2.0 doesn't keep folders named like Tags

### ISSUE THREAD

**Issue by gasparesganga** [jekyll/jekyll-assets#209]
The scenario is just like the one described in #161 : I have an `/_assets` folder and inside it some `css`, `js`, `img`, `fonts`, `foo`, `bar`.... folders.
In `config.yml`: 

    assets : 
      assets    : [*]
      sources   : [_assets]
      prefix    : /assets

It used to work like a charm in betas before release `2.0`. Now it seems that if a folder is named like a **Tag** (*ie:`css`, `js`, `img`*) the hierarchy won't be mantained, while using some folders names like `fonts`, `foo`, `bar` it still works as expected.

**Comment by envygeeks** [comment]
@gasparesganga I don't get what you mean, can you clarify a bit or provide and possibly provide an example as a repo I can clone and turn into a test case?

**Comment by envygeeks** [comment]
Which beta are you referring to as well.  The 2.0 beta on master that's been there for months or a beta that we released for 2.0 or a 1.0 beta?

**Comment by envygeeks** [comment]
I see what you mean now, if you set it to "_assets" you want the subfolder structure kept.  So you want "_assets/" as the primary source you want "css/file.scss" to be "/assets/css/file.css"?

**Comment by gasparesganga** [comment]
Exactly. My folder structure is `_assets/css/file.css` and using the tag 
`{% stylesheet css/file.css %}`
I would expect `/assets/css/file.css` as output, keeping the subfolder structure indeed.

PS: I was referring to `2.0.0.pre.beta1`.

**Comment by envygeeks** [comment]
Yes, that's probably the result of me appending sources rather than replacing them because there was a user who got caught by that.  I might add an option or just detect it, which would you prefer?

**Comment by gasparesganga** [comment]
Maybe the autodetection would be a more consistent behaviour *(as a user, I can't see why certain folder names should act differently)*, but any kind of solution would work for me: a config option, some kind of quoting/escaping in the tags and filters, etc.

**Comment by envygeeks** [comment]
Technically it's not behaving different, it's behaving exactly as it was designed, which is to use the sub-folders of your asset base folders as part of the path.  So if your base folder is _assets and you have css/* it will use css/* but if you have _asset/css as a base folder it will not use css as part of that path, that is a base asset folder.

What is happening here is that we *append* your path, not *prepend* your path, so it's actually pulling your assets from _assets/css before it searches _assets and assumes it's a sub-path... which intern strips your sub-directory and that sub-directory from your final path.

What we need to do here is detect if you want to use _assets as the base directory and if you do then remove our base directories instead of appending your base directory which will bring that back, otherwise you would have to do _assets/css/css/*.scss to get that back.

**Comment by gasparesganga** [comment]
Thanks for the clarification, I hadn't thought about it that way. But what puzzled me was the fact that when a subdirectory is named differently, it works. Also sub-sub-diretories are kept. Here is an example:

    _assets/css/file1
    _assets/css/x/file2
    _assets/dummy/file3

produces:

    /assets/file1
    /assets/x/file2
    /assets/dummy/file3

So both subfolder `dummy` and sub-subfolder `x` are kept. I assumed only the subfolders named like tags *(image, img, stylesheet, css, javascript, js, etc.)* were dropped.

**Comment by envygeeks** [comment]
Yes, that's the right behavior so here let me use those to exaplify the feature bug:

## Right now

```yaml
sources:
- _assets/
```

which results in:

```yaml
sources:
- _assets/css
- _assets/
```

Which results in Sprockets picking from `_assets/css` first, which means "css" is not a sub-directory so it's not going to be apart of the path which will result in: `_asset/css/file1 # => /assets/file1` which is the standard behavior, we did not detect a sub-folder, it was a base directory.

## Previously

```yaml
sources:
- _assets/
```

would result in:

```yaml
sources:
- _assets/
```

Which would result in Sprockets picking from `_assets` first which means that "css" is a sub-directory so it's going to detect that the path will ship as `/assets/css/file1`

The bug here was that a user added a custom folder but wanted to retain ours, it led to a couple dozen messages of me assuming they did something wrong but  they figured out that they added our folders back after I pointed out the config example, which resulted in it working, I considered that a bug so I started appending your sources rather than replacing ours.

What I need to do now is further address that bug through your bug by now grepping `_assets` in the sources list and replacing rather than appending in only on that scenario.  This way if you want to use our container as your base folder, then by all means do it.

That might actually also end up solving #195 for @igolden too because now I can tell him to set `_assets` as his sole source and the prefix to "/" and in theory it will do exactly what he wants.

**Comment by gasparesganga** [comment]
I didn't consider the default sources list (I also assumed they were replaced and not appended) thus I speculated about tag names, my bad.

Now it's all clear, thank you for the fix!
