### ISSUE TITLE
Unable to use values from _config.yml in SCSS

### ISSUE THREAD

**Issue by charliesneath** [jekyll/jekyll-assets#220]
I have the following in `_config.yml`:

```yaml
colors:
  - name: red
    hex: '#FF0000'
  - name: yellow
    hex: '#FFFF00'
  - name: blue
    hex: '#0000FF'
```

In `_assets/css/colors.scss`, I want to create classes for the colors as follows:

```ruby
{% for color in site.colors %}
.{{ color.name }} {
  color: {{ color.hex }};
}

{% endfor %}
```

When I do so, I get the following error:

```
Error in _assets/css/background-test.scss:6 Invalid CSS after "}": expected selector or at-rule, was "{% for color in..." 
  Liquid Exception: Invalid CSS after "}": expected selector or at-rule, was "{% for color in..." in _includes/head.html, included in _layouts/default.html
jekyll 3.0.1 | Error:  Invalid CSS after "}": expected selector or at-rule, was "{% for color in..."
```

Using my debug repo here: https://github.com/charliesneath/asset-test

**Comment by charliesneath** [comment]
@envygeeks Out of curiosity -- is the above something that you expect to be already working with `jekyll-assets`?

**Comment by envygeeks** [comment]
@charliesneath no... if I'm honest, I would expect it to crash like it did as that's liquid behavior.  I don't acutally know if you can do something that advanced with Liquid, I'm tempted to drag @fw42 into this conversation and hope he can shed some light but from where I stand, looking at that snippet, I would surely expect Liquid to not handle it as it's written.

The reason I haven't closed this as a WONTFIX is because I am curious as to whether or not there is a workaround, but it won't be coming from `jekyll-assets` because this is a Liquid problem (and I don't know if I even consider it a problem more than by-design.)

**Comment by envygeeks** [comment]
Ultimately though, with the way CSS works and what you want to do and the way Liquid works, it'll have to be your source that makes the change because there is nothing `jekyll-assets` can do for you here, but when I have a moment over the next week I'll surely look over the debug repo and see if I can find a workaround for you.

**Comment by charliesneath** [comment]
@envygeeks Got it, thanks for the explanation.

So I understand: the main issue is using this kind of Liquid operation in SCSS? 

I don't know if it matters, but it's possible to do this kind of thing in HTML files (looping through custom variables in _config), e.g. generate drop-downs:

```liquid
<select>
{% for site.colors %}
  <option value="{{ color.name }}">{{ color.name }}</option>
{% endfor %}
</select>
```

**Comment by envygeeks** [comment]
You are comparing Apples to Oranges.  HTML is not CSS, there are no rouge `{` and `}` in the middle of the loop and they are two different species even if standards by the same body.

**Comment by charliesneath** [comment]
Turns out the code works when it's not included in a SCSS partial.

In the original example, if the `{% for color in site.colors %}` loop is added to `main.scss`, it outputs the CSS styles as expected.

**Comment by envygeeks** [comment]
Unfortunately is gonna be a wontfix because it's an upstream issue.  All we do is register everything and it's up to sprockets to decide how it wants us to transform.  To fix this would dig is in way too deep into altering sprockets.
