### ISSUE TITLE
Use assets outside the _assets folder

### ISSUE THREAD

**Issue by nielsenramon** [jekyll/jekyll-assets#226]
I used to include assets from outside the _assets folder, but with the new version it's no longer working.

It used to work like this https://github.com/nielsenramon/stacss/blob/master/_config.yml#L19

Any idea if this is still possible right now?

I get the following error while running my Jekyll project right now:

```
Could not find the asset `application'
Liquid Exception: Could not find the asset `application' in _layouts/default.html
jekyll 3.0.1 | Error:  Could not find the asset `application'
```

`application` is the scss manifest file in the SCSS folder outside the `_assets` folder.

**Comment by valkjsaaa** [comment]
I found out that if you move content of `_sass` folder to your stylesheet asset folder, it will work just fine.

**Comment by envygeeks** [comment]
Please read the documentation, there is an explicit way to do this: https://github.com/jekyll/jekyll-assets#configuration if it is not within Jekyll's route it will not however work, and that unfortunately will never be a feature because we fall in line with Jekyll in that we always use `Jekyll#in_source_dir`.

**Comment by envygeeks** [comment]
I should also link to: https://github.com/jekyll/jekyll-assets#sources which is a more direct explanation.  And also note that if that doesn't work please ping me and I'll happily re-open the ticket and look into it but others use it successfully and it's how we actually get `_assets` in there too.

**Comment by nielsenramon** [comment]
@valkjsaaa I want the `scss` folder to be outside of the docs `_assets` folder.

@envygeeks Looks like the sources are not working for folders outside of the _assets folder. It could be a jekyll routing error as it is outside the docs folder.

You can see my changes here: https://github.com/nielsenramon/stacss/pull/3/files

It works now with the older version of Jekyll-assets and Jekyll tho.

**Comment by envygeeks** [comment]
@nielsenramon Whether or not it worked in legacy Jekyll Assets is not relvant as it's no longer maintained and you are not on that version (not to say I would fix a bug in it... I wouldn't.)

I believe the problem here is that you are doing `../scss` instead of just `scss`.  We do not set your asset folder relative to "_assets" we set your asset folders relative to `Jekyll#in_source_dir`

**Comment by nielsenramon** [comment]
@envygeeks No problem. Removing the `../` does not fix the problem tho. I guess I'll separate the docs from the actual code :) Thanks for the help!
