### ISSUE TITLE
excluded assets should not be written out

### ISSUE THREAD

**Issue by untra** [jekyll/jekyll-assets#248]
This may sound like a strange feature to request, but if assets are to be written into the `prefix` folder, and the asset path is listed in the `exclude` directory, then the asset should not be written.

For example, if my `_config.yml` looks like:
```yml
exclude:
  - "assets/styles.css"
assets:
  prefix: "/assets"
```
Then I should expect that `assets/styles.css` is not written.

In addtion, if my `_config.yml` looks like:
```yml
exclude:
  - "assets"
assets:
  prefix: "/assets"
```
Then I should expect that the entirety of the `assets` folder is not written.

_Why would someone put their assets folder in their `excluded` list?_ My multi-language plugin dynamically modifies the excluded list before kicking off multiple `site.process` jobs. Because jekyll-assets currently builds agnostic to the `excluded` list, It winds up writing files despite my efforts to exclude them.

**Comment by envygeeks** [comment]
I'm on the fence about this as I don't see what benefits it might bring.  Elaborate why your multi-language plugin needs to exclude our assets that the user wants included.

**Comment by untra** [comment]
The `exclude` configuration is the list where a jekyll user identifies what files they explicitly do not want written out into their site. Users should be able to expect that if they list files in `exclude`, they won't get written out.

Right now, jekyll-assets builds all assets agnostic to the `exclude` configuration. I think the `exclude` configuration should still apply when writing out the assets folder.

My plugin is able to quickly and easily ensure specified folders and files are only written once for the default language website by adding those files to `site.exclude` before kicking off `site.process`. This has worked because I could guarentee that a fie doesn't get written out if it's in the `excluded` list.

A workaround for my plugin would involve deleting the built `assets` folder for every non-default language. But If I'm supporting 4 languages, then I'm going to compile, minify, tag and writeout my assets 4 separate times, then deleting 3 of those folders! that's not right :frowning: 

Another alternative would be a mechanism to disable jekyll-assets asset compilation before `site.process` gets called. Perhaps a configuration flag, like:
```yaml
assets:
  prefix: "/assets"
  disable: true
```
to signify that assets compilation is not desired in this use-case. **Ideally, I would like to see some configurable mechanism to disable asset compilation, or at the very least prevent files from being written out.**

**Comment by envygeeks** [comment]
> The exclude configuration is the list where a jekyll user identifies what files they explicitly do not want written out into their site. Users should be able to expect that if they list files in exclude, they won't get written out.

That exclude parameter is for Jekyll.  We are under no obligation to care what Jekyll does, as we are an app that operates within the app to get stuff done.  We only tie in as little as we need to and otherwise we work independent of Jekyll and Jekyll works independent of us.  I can see a compelling reason to use it, but again, the argument that we ***should*** is flat out invalid.

> My plugin is able to quickly and easily ensure specified folders and files are only written once for the default language website by adding those files to site.exclude before kicking off site.process. This has worked because I could guarentee that a fie doesn't get written out if it's in the excluded list.

I still do not see what this has to do with us.  You couldn't guarantee any more than us that it's written only once because we are the ones who manage that file.  What exactly are you trying to say here?

> A workaround for my plugin would involve deleting the built assets folder for every non-default language. But If I'm supporting 4 languages, then I'm going to compile, minify, tag and writeout my assets 4 separate times, then deleting 3 of those folders! that's not right :frowning:

You broke the API and caused that edge, why am I responsible for that?

---

I'm not trying to be abrasive here, but it seems to me that you broke Jekyll's API and you expect me to backtrack and make it easy for you to push away from how Jekyll behaves by default to support features of which seem to be broken (to me.) A lot of these problems wouldn't exist if generators were used.  Then you want me to give you a feature to disable a feature the user wants, that'll never happen because the user wanted the feature and if they didn't want it they wouldn't install it.  It's not a default Jekyll Plugin, the user explicitly wanted this feature.

**Comment by untra** [comment]
>I'm not trying to be abrasive here, but it seems to me that you broke Jekyll's API and you expect me to backtrack and make it easy for you to push away from how Jekyll behaves by default to support features of which seem to be broken (to me.) A lot of these problems wouldn't exist if generators were used. Then you want me to give you a feature to disable a feature the user wants, that'll never happen because the user wanted the feature and if they didn't want it they wouldn't install it. It's not a default Jekyll Plugin, the user explicitly wanted this feature.

I'm starting to see that jekyll and jekyll-assets are very decoupled from each other. I was under the impression jekyll-assets would be more confined to jekyll configuration rules. 

If that's not the case, and there's no desire to implement an off-switch, then I guess this is a feature you don't want to see implemented. :confused:

**Comment by envygeeks** [comment]
I've thought about it and I'll concede to an option name change to "build: false" or "automatic_build: false" (neither of which I have settled on) which is in essence what you want but labeled differently as to it's intent.  I do not agree that we should ever implement an exclude list, we are an explicit build system, we do find all assets but only write that of which the user wants so that's definitely something I still don't agree on because it opens up a whole new world of behavior I don't quite understand is necessary.

**Comment by envygeeks** [comment]
I'll flag this for the next release and implement the option as it's easy to implement and takes no effort.

**Comment by envygeeks** [comment]
Hulk: today
