### ISSUE TITLE
Long list of documentation suggestions

### ISSUE THREAD

**Issue by jappareti** [jekyll/jekyll-assets#249]
I'm struggling with the documentation, but it might be because I'm newer to Jekyll and gems.

My main questions are:
- How do you reorganize the folder structure to support jekyll-assets?
- What should my css, js and img tags be changed to?
- How do I use an image in a sass file?
- Should I add `/.asset-cache` and `/.sass-cache`/ to `.gitignore`?
- Do I need to add `gem "uglifier"` to my Gemfile to compress js files?
- How do you "add" an "add-on"?

I know this is a lot and maybe these answers are obvious, but I don't think it would hurt to spell them out better in the documentation for newbies like me.

For example, with my first question, here's the default folder structure for Jekyll 3:

````
├── _config.yml
├── _includes
├── _layouts
├── _posts
├── _sass
│   ├── _base.scss
│   ├── _layout.scss
│   └── _syntax-highlighting.scss
├── css
│   └── main.scss
├── feed.xml
└── index.html
````

Should the new structure be this?
````
├── _config.yml
├── _includes
├── Gemfile
├── Gemfile.lock
├── _assets
│   ├── _sass
│   │   ├── _base.scss
│   │   ├── _layout.scss
│   │   └── _syntax-highlighting.scss
│   ├── css
│   │   └── main.scss
│   ├── img
│   └── js
│       └── main.js
├── _layouts
├── _posts
├── feed.xml
└── index.html
````

How would I update my `head.html` file to refer to my css file? This is the default:
`<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl }}">`

Should it be this?
`<link rel="stylesheet" href="{% css main.css %}">`

I could go on, but you probably get the idea.

**Comment by 2474** [comment]
- How do you reorganize the folder structure to support jekyll-assets?

Some one more knowledgeable can correct me if I am wrong but I believe it's a railsy way of handling assets. At the end of the day and asset is an asset so they typically just go in the assets folder. You can however have subfolders. I have found that if I have a set up like:

```
_assets/
  images/
   img/
     ...
  scripts/
    js/
      ...
  styles/
    css/
      ...
```
 I usually need to reference the file by `{% img 'img/imageName.jpg %}`, `{% css 'css/styles.css' %} or`:

```
.exampleClass {
  background: url(asset_path('img/imageName.jpg'));
}
```

- How do I use an image in a sass file?

```
.exampleClass {
  background: url(asset_path('img/imageName.jpg'));
}
```

The example above should help

- Should I add /.asset-cache and /.sass-cache/ to .gitignore?

I would. Don't think you really need to push caches files.

- Do I need to add gem "uglifier" to my Gemfile to compress js files?

Yes, and it should only uglify when building for production unless you specify otherwise with  `JEKYLL_ENV=production jekyll build`. Here is my small Gemfile for a project I'm working on

```
source 'https://rubygems.org'

gem 'jekyll'
gem 'kramdown'
gem 'jekyll-assets', :github => 'jekyll/jekyll-assets'
gem 'uglifier'
gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'mini_magick'
gem 'nokogiri'
```

- How do you "add" an "add-on"?

If you are referring to the Jekyll-Assets add-ons you should be able to just add the gems to your gemfile and follow the instructions on how to use each add-on.

**Comment by envygeeks** [comment]
> How do you reorganize the folder structure to support jekyll-assets?

All your assets go into `_assets/{images,stylesheets,javascripts}`, you can also opt to just use `_assets` for everything, or you can keep your current structure if you want... by adding those folders to our assets list (as provided in the README.md at https://github.com/jekyll/jekyll-assets#sources)

> What should my css, js and img tags be changed to?

This is a broad question.

> How do I use an image in a sass file?

You use the asset helpers provided by us to SASS as mentioned in the documentation: https://github.com/jekyll/jekyll-assets#sass-helpers

> Should I add /.asset-cache and /.sass-cache/ to .gitignore?

That is up to you.  I do not when stored in public git, but on our build servers we do make sure it's included so when we port a site across servers they do not lose their caches.  Whether or not you decide to add it to git is a merit you will have to decide.

> Do I need to add gem "uglifier" to my Gemfile to compress js files?

Yes.

> How do you "add" an "add-on"?

If the addon is listed in our README (https://github.com/jekyll/jekyll-assets#addons) then you add it's dependency to your Gemfile and install it and we will load it when you use it, or we need it.  For example if you do not provide uglifier then we do not use it, even if you ask us to.  If you add it, then as @2474 said, we will only load it in production when we need it.

*in addition to those on that list we support uglifier, and anything that sprockets supports as long as it does not compromise our integrity (such as Erb would -- we intentionally block your access to Erb.)

**Comment by envygeeks** [comment]
This issue is being closed for lack of a response in return.  If you are still having a problem please ping via this ticket and it'll be reopened for you and further feedback will be sough.  Thanks.
