### ISSUE TITLE
Enhancement: magick:gravity:<value>

### ISSUE THREAD

**Issue by 2474** [jekyll/jekyll-assets#254]
Would be nice to be able to set the gravity of the crop (`magick:gravity:center`) so you could do center crops with `magick:crop:400x300+0+0` for example.

**Comment by 2474** [comment]
@envygeeks, I didn't want to start a new issue for this but after this was added I wanted to test the proxy. Currently I'm just using it like:

`{% img 'image.jpg' magick:gravity:center magick:crop:600x400+0+0 %}`

Mini Magick suggests combining options which is looks like `magick.rb` does below:

`magick.rb`
```
def process
      img = MiniMagick::Image.open(@path)
      private_methods(true).select { |v| v =~ /\Amagick_/ }.each do |method|
        send(method, img)
      end

      img.write(
        @path
      )
    ensure
      img.destroy!
    end
```

However my images are still being cropped from the top left corner. Image Magick suggests the following for cropping from the center:


> The most common use of a gravitated crop, is to crop the 'center' of an image.
> 
> `convert rose:  -gravity Center  -crop 32x32+0+0 +repage  crop_center.gif`

Which is why I thought `{% img 'image.jpg' magick:gravity:center magick:crop:600x400+0+0 %}` might work? Any insight or guidance would be appreciated. Apologies if this doesn't end up being related to jekyll-assets.

**Comment by envygeeks** [comment]
We only pass-through options.  If it's not working as expected that seems like a Minimagic bug to me, if it expects them in a certain order that again is a mini-magic problem because this is Ruby, we have no way to guarantee a hash will come in a specific order and adhering to such a crazy idiom is something we will never do (as it's up to them to order it the way they want if they expect that.)

That said, I see a disparity between what ImageMagick wants and what you send.  They use "Center" you use "center", in my experience ImageMagick is pretty strict about what it wants (for good reason since it's a complicated piece of software that has wrappers for it's wrappers to make it easier.)

**Comment by 2474** [comment]
@envygeeks, Thanks for the quick response. I wish it was the `center or Center` but I've tried both with the same results. 

I may send Mini Magick a message just to see if that is the case. Push comes to shove I guess I'll have to do some manual image manipulation but I guess things could be worse.

Not sure how you want to proceed but that's the case I can't see a real use for `magick:gravity:<value>`

**Comment by 2474** [comment]
@envygeeks What are your thoughts about this? He also suggested a possible solution [#362](https://github.com/minimagick/minimagick/issues/362). Thanks for your help this far.

**Comment by envygeeks** [comment]
https://github.com/jekyll/jekyll-assets/commit/ccde62ebe1749013f20cc5e2373bf282a85cc322
