### ISSUE TITLE
(Minor Documentation Issue) `magick: 2x` is not supported

### ISSUE THREAD

**Issue by tohuw** [jekyll/jekyll-assets#274]
In the [Filters](https://github.com/jekyll/jekyll-assets#filters) section of the documentation, `magick: 2x` is included as an example, but this is not actually a supported value!

**Comment by envygeeks** [comment]
Yes it is: https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/proxies/magick.rb#L9 https://github.com/jekyll/jekyll-assets/blob/master/spec/tests/lib/jekyll/assets/addons/proxies/magick_spec.rb#L77.  we do not support spaces between key and value because we part like your CLI does so "magick:" and "2x" are each their own so you'll end up with "2x=true" on your HTML tag (or an error sometimes.) It needs to be "magic:2x" for it to work.

**Comment by envygeeks** [comment]
If you continue to have problems, do please let me know and I'll happily investigate further.
