### ISSUE TITLE
How to resize an image?

### ISSUE THREAD

**Issue by chalmagean** [jekyll/jekyll-assets#289]
I've been trying to resize an image with no luck. I've looked over the issues in here and tried everything but still, I can't resize an image. Why is this so hard? How can I do a resize?

Here's what my code looks like:
```
---
image-preview: blog/image.png
---
{% img '{{ post.image-preview }}' alt:'{{ post.title }}' class:'blog-preview-image' %}
```

Jekyll (3.1.2)
Jekyll-assets (2.2.7)

Thanks

**Comment by chalmagean** [comment]
So the issue was, I didn't have the `mini_magick` gem installed and so I was always getting the original file path (no digest). By installing `mini_magick` resize works fine.

This should probably be part of the docs. It took me a while to figure out.

**Comment by envygeeks** [comment]
> This should probably be more obvious in the docs

Submit a pull request to correct the problem then please, it's pretty obvious to me and you are one of the few people who hasn't spotted it under the addon's banner.  I'm not saying you're wrong but I'm saying that in order for documentation to be corrected everybody has to chip in with their own perspective because the docs are very clear to me so it would be nice if you would send a PR to clarify what you wish clarified or add what you think should be added.

**Comment by chalmagean** [comment]
I'll submit a PR
