### ISSUE TITLE
how to call image_optim for all image assets after all transforms

### ISSUE THREAD

**Issue by tomas-zemres** [jekyll/jekyll-assets#297]
I am looking to https://github.com/jekyll/jekyll-assets/issues/243 and https://github.com/jekyll/jekyll-assets/issues/141, but a I am not sure if it is same issue.

I am trying use Sprockets.register_preprocessor(...) with image_optim, but the image_optim is called before transformations like "magick:resize:100x100". Final filesize of images is much more bigger than if image_optim is called on resized images.

Is it possible register some post-processing function that will be called after all "magick:*" transformations and before generating assert-sha-digest?

Nice would be if generated asset-sha-digest on production will be changed if optimizer-parameters are changed.

**Comment by envygeeks** [comment]
@tomas-zemres we don't use transformers for magick and you shouldn't use one for image_optim either, Magick a proxy, so it skips Sprockets entirely for the most part, other than finding the asset and it's path, past that point it goes into a proxy (which is why it's called a proxy) that proxies between Sprockets and said proxy to do what it needs to do. There is no way for you to think your plugin is more important than another, it's up to the author to decide that by the order they put their proxies in.

That said, I don't know what "assert-sha-digest" is to you but our digests are based on the final result of the cache inside of .asset-cache 100% of the time for Proxies, so if you change "magick:resize:100x100" the digest *will* change.  If you mean change the digest based on other arguments that don't affect the actual data, that's going to require a ticket and consideration because it's upstream that handles non-proxy data, not us and I don't know if I am willing to take on that responsibility because we've already Sprockets 4 coming quickly and I do not wish to impede the move any further.

All that said, if you wish to help out with that issue, it would be preferable you use a proxy to do it, users want arguments, it should have arguments, there is no one fits all even if there are defaults and options.  If you want to see how proxies are implemented you can look here: https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/proxies/magick.rb

**Comment by tomas-zemres** [comment]
Thank you for advice. I implemented simple `_plugin/assets_optim_proxy.rb`

```ruby
require "jekyll-assets"
require 'image_optim'

Jekyll::Assets::Env.liquid_proxies.add :image_optim, :img, 'optimize' do

  def initialize(asset, opts, args)
    @path = asset.filename
    @image_optim = ::ImageOptim.new();
  end

    def process
    @image_optim.optimize_image!(@path)
  end
end
```

Then I must put `image_optim:optimize:1` it to `{% img %}` args, for example:
 `{% '0010966.JPG'  magick:resize:'2048x2048' image_optim:optimize:1 %}`

I works correctly.

**Comment by alexey-pelykh** [comment]
@envygeeks Maybe #408 would be useful here

**Comment by envygeeks** [comment]
We now support `image_optim` thanks to @alexey-pelykh
