### ISSUE TITLE
Append assets to `site.static_files`

### ISSUE THREAD

**Issue by joeyhoer** [jekyll/jekyll-assets#307]
I'm trying to create a list of all scripts/images on the site to accomplish something like:

https://github.com/ebello/jekyll-perf/blob/master/manifest.appcache
https://github.com/ebello/jekyll-perf/blob/master/_plugins/sorted_nav.rb#L23

In version 1.X assets were appended to `site.static_files`, this appears no longer to be the case.

https://github.com/jekyll/jekyll-assets/blob/1.0-legacy/lib/jekyll/assets/patches/site_patch.rb#L54

There is a much older issue that could be related to this issue which is closed: https://github.com/jekyll/jekyll-assets/issues/101

---

The `{{ assets }}` variable contains too many files (all of the SCSS partials), though I did try iterating over that with pure liquid:

```
{% for item in assets %}{{ item[1].logical_path }}
{% endfor %}
```

This (I believe) is attempting to compile each Sass partial, resulting in a `Liquid Exception: Undefined mixin` error.

Is there a correct way to do this with `jekyll-assets`, perhaps via hooks?

**Comment by envygeeks** [comment]
We've no hooks that happen after everything is done so this will require a new hook unless you hit up `jekyll.sprockets.all_assets` which is deprecated and will be removed in favor of manifests in 3.0 so this'll take some thought.

**Comment by envygeeks** [comment]
After further thinking, I don't even think we can pull an asset without Sprockets taking over and compiling it or trying to; I don't know if I'm even willing to support this before 3.x since there are bigger problems on our plate, like Sprockets 4.x support.

**Comment by joeyhoer** [comment]
In my use case, I'm trying to retrieve a list of only post compiled assets (I wouldn't want all the Sass partials, or images that have not been used) for example, so generating an index of files post-processing would be ideal.

**Comment by envygeeks** [comment]
The problem here is that I assume Jekyll will try to write them, unless @parkr, @mattr-, or anybody on @jekyll/core can let me know this will be the case, I doubt we will ever support this feature.  The second problem here is that we actually run ***after*** Jekyll is done running, and we process, and work entirely indepdendent of them, so working in `site.static_files` probably won't work.  We do however provide `site.assets` that you can get a list of assets (before they are compiled.)

I don't know that we can reliably support this feature as it would require us to either work ***before*** Jekyll or to start doing much more work than I feel we should be doing.  We do not wish to deeply integrate with Jekyll in that kind of way because I feel it would impede both parties and make it so that Jekyll-Assets has to keep up with Jekyll, whereas most of the time this library works with minimal to no changes between Jekyll versions.

**Comment by envygeeks** [comment]
Unfortunately I don't feel we should do this.  At this time and the community at large has shown no interest, however if that changes I'll be happy to reconsider.

**Comment by envygeeks** [comment]
We have provided this since the beginning: https://github.com/jekyll/jekyll-assets#dynamically-loading-assets

**Comment by joeyhoer** [comment]
Looks like we've come full circle.

Unfortunately, the `{{ assets }}` variable contains too many files, including pre-compiled assets (e.g. all of the SCSS partials), and does not contain the post-compiled URLs. I did try iterating over the `{{ assets }}` object with pure liquid:

```
{% for item in assets %}{{ item[1].logical_path }}
{% endfor %}
```

However, this is still resulting in a `Liquid Exception: Undefined mixin` error. I believe this is because Jekyll assets is attempting to compile each Sass partial independently.

It sounds like there is no good solution to this problem at present, and that a solution might require significant rework in the core of `jekyll-assets`.

**Comment by envygeeks** [comment]
In 3.x

```
{% for item in assets %}
   {% asset "{{ asset.filename }}" @path %}
{% endfor %}
```

We have no concept of Partials, unlike Rails.  We only have a concept of an asset.  I'll adjust our `assets` variable to exclude anything with an `_` at the beginning which is a typical partial.

**Comment by envygeeks** [comment]
I'll reopen this and add a few more methods on our stuff and adjust it slightly as it won't stop the release.

**Comment by envygeeks** [comment]
This is fixed in 3.x, we've stripped the path even further, made it so that partials aren't included and made digest_path return the prefixed digest path so that you can work with everything easier.
