### ISSUE TITLE
Changing the `digest_path`

### ISSUE THREAD

**Issue by xcambar** [jekyll/jekyll-assets#329]
Hi,

as per https://github.com/jekyll/jekyll-assets/blob/6eeb51fa35b2d7d8cf8335cd203e2d66848ea5fb/lib/jekyll/assets/liquid/tag/proxied_asset.rb#L105-L107, the naming convention for an asset when `digest: true` is `./path/to/filename-DIGEST.ext`.

I'd like to be able to change this, for example: `./DIGEST/path/to/filename.ext`.

I didn't find anything in jekyll-assets to do so, but I'd like to know if you'd think of a workaround towards this goal.

Cheers!

**Comment by envygeeks** [comment]
At this time we don't have that capability, we use Sprockets itself to generate the Digest path and in-order to do what you requested we would have to take over their pathing (we do in a few places but only to replicate what the upper level assets do.) 

I'm not against this idea, if it's easy (or if somebody else wants to take a stab.) However, I think it should wait until we get Sprockets 4.0 implemented in the next month because that's already a lot of work to get done (Sprockets 4.0 has a ton of changes we've to account for.)

**Comment by xcambar** [comment]
👍  I can give it a try and/or wait for the next month, whichever comes first. Let's see how it goes. 

Meanwhile: glad you like the idea.

**Comment by envygeeks** [comment]
Sorry for never updating you, we've supported a `prefix` for quite sometime, you can now customize where your assets are placed.  Even if we add a CDN and so-forth.
