### ISSUE TITLE
Understanding JekyllAssets

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-assets#331]
Hi, 
I'm a fairly new Jekyll user. (started using Jekyll from v3.2). I came across JekyllAssets when I started to explore available options to using assets with a new Jekyll blog.

Naturally, I read the README to grasp the concept behind this plugin. Sadly, I had a hard time understanding what the document intended to convey.
- `README` instructs (users) to **move** `css/main.css` to `_assets/css` but `jekyll new` generates `css/main.scss`. `css/main.css` is only generated by `jekyll build` / `jekyll serve` .

okay, assuming its a typo, I _move_ `css/main.scss` to `_assets/css`, (hence becoming `_assets/css/main.scss`)
- `README` then instructs to edit `_includes/head.html` to include the plugin's liquid tag. Since _includes are no longer available out-of-the-box, I create `_includes` at the blog root, and copy `~gems/minima/_includes/head.html` to it, and edit as required.

I go ahead and start a jekyll server and head to localhost.
I see that the main.css has returned a `404 error`

I add `sources:` to config file and remove front matter from `main.scss` (no error/warning was thrown saying that sprockets did not understand them, btw). 
Then restarted the Jekyll server. Still no stylesheet loaded.

I then added an html comment next to `{% css main %}` : `<!-- jekyll-assets tag -->`

The page is regenerated and still the same. Only, now I realize that jekyll has loaded the original vanilla head.html from minima instead of the one i placed at the blog root.
- The `README` doesnt mention anything about not supporting gem-based themes.

**Comment by envygeeks** [comment]
> okay, assuming its a typo, I move css/main.scss to _assets/css, (hence becoming _assets/css/main.scss)

It's not a typo, I just don't care because there are over a dozen extensions we can support, it's simply just an example that's meant to guide you, not  a copy and paste.  The user must fill in a bit with their own guesses and knowledge. Though, if it bugs you, I'm happy to accept a pull request, especially if you think it will help the user more! :laughing: 

---

> The README doesnt mention anything about not supporting gem-based themes.

We don't support Gem based themes and we won't until they improve their API or I am willing and able to take the time to dig through @benbalter's source to see how I can extract the paths necessary to support them and even then it will be up to Jekyll and the Gem Author to support Jekyll Assets in their actual theme, in that they'll need to actually route through us otherwise it is all entirely meaningless.

Gem based themes are new and this software is extremely stable (in that we have thousands of users and get very few bug tickets...) I do not wish to disrupt that by adding in an unstable feature before I completely understand it as it will result in more builds that shouldn't be necessary... sure I believe in shipping fast but not that fast.  That said it's unstable in that I think it could probably use a bit more outer support for plugins, not unstable in that it's actually unstable and doesn't work.  I don't use it but the people I know who do use it, appreciate it and love it.

> The page is regenerated and still the same. Only, now I realize that jekyll has loaded the original vanilla head.html from minima instead of the one i placed at the blog root.

This is an upstream bug, and should be addressed by Jekyll, not Jekyll-Assets and this part of the problem.  Though I don't consider it a bug, it's a feature request so you should flag it as so.  You should /cc @benbalter since it's his feature, I'll chim in with my support for it too because if I ever use Gem based themes on any of my projects this will be a requirement because boilerplate rarely if ever suffice.

**Comment by ashmaroli** [comment]
Thank you Jordon, for the detailed response.
 
> it's simply just an example that's meant to guide you, not a copy and paste. The user must fill in a bit with their own guesses and knowledge. 
>
> --
> We don't support Gem based themes

_IMHO_, installation / getting started documentation should be a breeze to walkthrough for every kind of user, uninitiated/novice/intermediate/experienced.
That said I wont be opening a PR myself (as of now, maybe sometime later.)

**Comment by benbalter** [comment]
@envygeeks thanks for the detailed analysis. Just to clarify, I may have spiked out the initial PR, but it's part of Jekyll core now and belongs to the community. If you see any opportunities to improve the theme API I'd be more than glad to help review pull requests to make it more flexible or provide better plugin support. 😺

**Comment by envygeeks** [comment]
> installation / getting started documentation 

I'll digress, it should be, however, I am a programmer for programmers so my documentation tends to be written as if I programmed this for another programmer and to the average user it probably is lacking considerably compared to what it should be.  I look to the community to help me improve this documentation as upstream does to improve theirs as it all reads clearly to me and the people I originally took this over for.

**Comment by envygeeks** [comment]
We have significantly improved the documentation for 3.x.

We now support Jekyll style `---`, we now provide instructions on how to move between the two, we now provide much more details about Sprockets, Jekyll, configuration, plugins, integration and much more.

**Comment by ashmaroli** [comment]
I've not read through the improved documentation, but thank you for putting in time and effort towards it :+1:
