### ISSUE TITLE
JekyllAssets and Jekyll 3.3

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-assets#338]
I understand JekyllAssets is a very stable module. But i'd like to know, if this plugin is compatible for basic content-creators running a site built with jekyll 3.3 and linked to a theme gem

**Comment by envygeeks** [comment]
We don't and cannot support Gem themes until @benbalter improves the API on Gem themes so that theme authors can add Jekyll Assets to their stack, there is nothing we can do about it right now sadly.  We will remain compatible with Jekyll 3.3 for t he content creators though so if they add Jekyll Assets and use it for their own assets, things will work as planned.

**Comment by ashmaroli** [comment]
> until @benbalter improves the API on Gem themes

what needs to be changed, if I may ask?

**Comment by Stargator** [comment]
@benbalter Any update on this?

**Comment by benbalter** [comment]
> We don't and cannot support Gem themes until @benbalter improves the API on Gem themes so that theme authors can add Jekyll Assets to their stack, there is nothing we can do about it right now sadly

What needs to be changed? Anyone interested in putting together a Pr?

**Comment by envygeeks** [comment]
I don't remember what needs to be changed, I'll carve out some time this week to review both and see what I was talking about, the Gem API has changed a bit since then but right off the bat,I can tell that the Gem API will need to accept a callback for us to ship the right asset.

**Comment by envygeeks** [comment]
Going to close this so that we don't have tickets laying around.  If the API ever improves we will try our best to support Gem themes, until then we just don't have the option.
