### ISSUE TITLE
Conflict with `where` filter and document titles which contain spaces

### ISSUE THREAD

**Issue by sskylar** [jekyll/jekyll-assets#340]
Ran into a strange bug which I traced back to a conflict with jekyll-assets. It's not clear to me why jekyll-assets has any effect on this functionality, but let me explain...

I put together a full demonstration with source code: https://github.com/sskylar/jekyll-assets-where

For context, we have 2 documents: one with spaces in the title, one without. Using the Jekyll `where` filter, we should be able to return either of these documents (nothing strange here):

```
{% assign doc = site.docs | where:'title','Titlewithoutspaces' | first %}

{% assign doc = site.docs | where:'title','Title with spaces' | first %}
```

Of course, this works as expected **without** jekyll-assets enabled. However, only the first example works **with** jekyll-assets enabled.
## Without jekyll-assets

1) Grab [source code](https://github.com/sskylar/jekyll-assets-where) and run `bundle install` with jekyll-assets **disabled**:

```
source 'https://rubygems.org'
gem 'jekyll'
# gem 'jekyll-assets', group: :jekyll_plugins
```

2) Run `bundle exec jekyll serve` and visit http://localhost:4000

The `where` filter behaves as expected.

![](http://drp.mk/i/yFT9fVkL87.png)
## With jekyll-assets

1) Run `bundle install` with jekyll-assets **enabled**:

```
source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-assets', group: :jekyll_plugins
```

2) Run `bundle exec jekyll serve` and visit http://localhost:4000

Notice how the `where` filter is able to find single word matches, but not multiple word matches:

![](http://drp.mk/i/Q28FC4KsS.png)

I should note that while `where` is affected by jekyll-assets, `where_exp` is not affected. This works as expected:

```
{% assign doc = site.docs | where_exp:'item','item.title == "Title with spaces"' | first %}
```

I don't see any reason why jekyll-assets should care about my document titles as they are not related to assets, so I feel like this is a bug.

**Comment by envygeeks** [comment]
If Jekyll Assets messes with a filter I'm gonna have to say it's an upstream bug in either Liquid or Jekyll itself.  AFAIW (and I wrote the source for Jekyll Assets 2.0+) we do not mess with the state of Jekyll at all.  We go out of our way to avoid the raw state of Jekyll except for `config.assets` and we minimally alter that.

Other than that we work outside of Jekyll and the only time we use Jekyll's own filters are when we bring them inside of Liquid for our own `.liquid` extension and if that alters the state of Jekyll or Liquid that really is an upstream bug as it shouldn't.  We do that here: https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/processors/liquid.rb#L18-L22 We also use a hook to add `site.assets` but again if that messes with filters there is a much bigger bug that is outside of Jekyll Assets.

> I don't see any reason why jekyll-assets should care about my document titles as they are not related to assets, so I feel like this is a bug.

We don't, so much that we don't even know they exist in Jekyll Assets context, we don't care about Jekyll at all really.  I know this is called Jekyll Assets but the truth of it is, we give Jekyll a list of our own filters, and tags and then after that we don't operate within Jekyll, we don't look through Jekyll for assets, we don't hit any objects within Jekyll other than `config`, we don't care about pages, documents, static files or otherwise, we operate that outside of Jekyll with Sprockets itself, we give it a path and it does the reset outside of Jekyll.  Like I said, we go out of our way to stay out of Jekyll's way and we request the same of Jekyll, we have separate concerns.

**Comment by envygeeks** [comment]
I'm happy to look into this bug, but really, I don't think this is our bug, but since I know both Jekyll and Jekyll Assets I can see where it could possibly originate and what could be causing it so I can be 100% sure, and at that time I'll either refile or fix the issue here.

**Comment by envygeeks** [comment]
This is fixed upstream in extras and will be released today or tomorrow morning.
