### ISSUE TITLE
site var does not include Jekyll-Assets css created by Saas

### ISSUE THREAD

**Issue by git-no** [jekyll/jekyll-assets#349]
Jekyll assets, like css are not available in Jekyll static_files nor documents.

E.g. site.static_files in ```Jekyll::Hooks.register :site, :post_write do |site|``` does not have ```/assets/main.css```but main.css does exists in _site/assets, created by Jekyll-Assets.
main.css is generated by Jekyll-Assets from .scss file. The layout file for the HTML header includes     ```{% css main %}```tag.

Result/impact: Jekyll site.documents, site.static_files does not list documents created in _site by Jekyll.

My ruby plugin code has:
```ruby
@pages = Array.new
site.pages.each { |item| @pages << item }
site.posts.docs.each { |item| @pages << item }
site.documents.each { |item| @pages << item }
site.static_files.each { |item| files << item.url }
```

Tested with v2.2.8.
Let me know in case this is a Jekyll issue. I would transfer this case to Jekyll Issues.
Thank you.

**Comment by envygeeks** [comment]
Jekyll-Assets does not use the "/assets" folder inside of your Jekyll root, and we have no plans to do so any time soon.  That file doesn't show up because that path is not valid to us.  If you wish your file to show up move it to "_assets/css" or otherwise, or add "/assets" to your allowable paths.
