### ISSUE TITLE
Deleting _site confuses cache

### ISSUE THREAD

**Issue by cameronmcefee** [jekyll/jekyll-assets#371]
I'm not 100% sure I actually know the cause of this issue, but here's what I've been able to piece together.

A coworker recently started using our Jekyll blog with Vagrant and started to see that our font assets don't work. After some testing, I was able to figure this much out:

1. On the first run of Jekyll, the font files get copied to the assets folder as expected.
2. If I stop the server, delete `_site`, then run the server again, all assets **except** the fonts get rebuilt to the assets folder, causing 404s.

I've been able to get around the issue by setting `cache: false` in the config. I can't reproduce this issue when I run the blog locally (not using Vagrant). However, I have noticed that when running a Jekyll server for extended durations new image files don't get generated, and some old ones don't regenerate.

All this has lead me to believe that mucking with _site may have some sort of impact on binary files in the cache. I tried digging in the source to see if I could debug it myself, but the cache stuff is a little above my pay grade.

Hopefully this is enough to go on, but I won't be offended if this gets closed as an unhelpful bug report since I can't reproduce it concretely.

**Comment by envygeeks** [comment]
I know there are issues with Vagrant in general (and not because of Vagrant but because of VirtualBox and Oracles refusal to come out and admit and fix several files system issues they have.) There are times were CSS won't get generated by SASS and Jekyll as a whole.

As far as `_site` messing with Assets, there is a small chance for a race on some file systems (especially within VirtualBox) where we will possibly detect a file before it's removed and not write the file but it's removed because we move faster than the virual machine does.  There could have also been a change in Jekyll that I need to look at too, where certain things that used to happen no longer happen.

There are no promises I'll get anywhere because this is a pretty broad bug (and I can't really fix the vagrant issues -- until we upgrade to Sprockets 4.x) but I'll take a look when I have some time.

**Comment by cameronmcefee** [comment]
Damn, that's a shame (about the Oracle stuff). If you do look into it though, good luck! Disabling the cache seems to be working well enough for us, so we're good over here for now.

**Comment by cameronmcefee** [comment]
I've been doing some more work on another site which isn't set up with vagrant and am reliably reproducing the issue.

Example of the structure

```
/src
  index.html
  /_assets
    /fonts
      /webfont
        webfont.woff
```

1. Run jekyll first time: fonts get copied over
1. rm -rf _site
1. Run jekyll again: fonts 404
1. rm -rf .asset-cache
1. Run jekyll again: fonts get copied over

**Comment by envygeeks** [comment]
Seems like a bug in our caching source, thanks for the update, that pinpoints the problem.

**Comment by clody69** [comment]
Same problem. Disabling the cache fixed it.

**Comment by abeMedia** [comment]
Any ETA on this? I'm having the same issue...
Disabling cache isn't really an option as there are many images which are resized, cropped & optimised so it would bring the build time from a few seconds up to a good 10 minutes!

**Comment by kylekirkby** [comment]
I am having the same issue where sometimes the assets are copied over and other times they are not. This happens when using the asset_path in my sass partials. Any updates on this issue ?

**Comment by envygeeks** [comment]
This is fixed in 3.x, we take full advantage of Sprockets Manifest in 3.x since they finally fixed a lot of the quirks that stopped us in 2.x.

Thanks!
