### ISSUE TITLE
Can't @import stylesheet.scss.liquid

### ISSUE THREAD

**Issue by cameronmcefee** [jekyll/jekyll-assets#374]
Is it possible to `@import` a file that has been preprocessed with liquid? Given:

sheet-a.scss
```css
@import "sheet-b"
```

and 

sheet-b.scss.liquid

```css
/* {{ site.title }} */
```

You'll get

`Error: File to import not found or unreadable: sheet-b.scss.liquid`

Removing `.liquid` fixes the issue but removes the preprocessing.

**Comment by envygeeks** [comment]
TBQF I don't know, I'll take a look in a few days but at this point I think this might be an upstream bug?

**Comment by envygeeks** [comment]
This is a blocker for 3.x

**Comment by envygeeks** [comment]
After thinking about this issue, this is actually expected behavior with SASS and Sprockets.  If you wish to preprocess the files you have to actually use Sprockets to do it `//=require path/to/file` which at that point should work.  I don't think Sprockets works that deeply with SASS internals.

I feel it's better to let people know via documentation that you need to use Sprockets requires in order to preprocess with Liquid and would prefer us not to jump into that kind of rabbit-hole here as we are trying to reduce the amount of extra work we do ontop of Sprockets now that 4.x is out and it's pretty awesome compared to the old 3.x.
