### ISSUE TITLE
Mixed Sass Scss imports.

### ISSUE THREAD

**Issue by HaoZeke** [jekyll/jekyll-assets#397]
Several issues.

First, the asset paths don't seem to look into the subfolders.
More importantly, while importing some sass files in an scss main file,

Error in _assets/styles/bulma/bulma.sass:6 File to import not found or unreadable: sass/components/_all.

The actual file is _all.sass

This compiled fine in jekyll. Not working since I switched to assets.

The issue can be replicated in any jekyll docker image as well.

**Comment by envygeeks** [comment]
> First, the asset paths don't seem to look into the subfolders.
> More importantly, while importing some sass files in an scss main file,

This is not a bug, we won't be fixing this.  Add the subfolder name to your import or inclusion.

> This compiled fine in jekyll. Not working since I switched to assets.

This is not Jekyll, this is Jekyll Assets, I don't build my software to behave like Jekyll does, and I never will.  That said, I don't even know if we support SASS or not, that is a question that should be asked upstream to Sprockets itself because SASS/SCSS is all handled by them.

> The issue can be replicated in any jekyll docker image as well.

This is not Jekyll Docker.

**Comment by HaoZeke** [comment]
Apologies...
Actually it turns out this is the default upstream behavior:

Jekyll does not include files starting with an underscore _, so _all.sass is ignored.

Including them manually as per the instructions here works:
https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
