### ISSUE TITLE
Calling magick with resize at 100x100 Yields Unexpected Result Size

### ISSUE THREAD

**Issue by tohuw** [jekyll/jekyll-assets#399]
jekyll 3.5.1, jekyll-assets 2.3.2

This seems to always yield a resulting image the same size as the original:
    {% img '/src/path' magick:resize:100x100 }

This results in a 101px square image:
    {% img '/src/path' magick:resize:101x101 }

Is this some nuance of [imagemagick resize](https://www.imagemagick.org/Usage/resize/) that I was previously unaware of? I can't recreate it with imagemagick alone, so I assume it to be within jekyll-asset's implementation. A Ruby expert I am not, but I'll try to find the offending code if I can. It seems I can reproduce this consistently.

**Comment by envygeeks** [comment]
Jekyll-Assets doesn't implement the magick directly, we use MiniMagick to do such things. We pass your values onto MiniMagick without altering them so I don't assume it's a fault of Jekyll-Assets unless somehow we are not running the proxy or the proxy is failing... or our images aren't saving/returning the cache properly.  If there is a hash then I would assume it's been proxied properly, but the easiest way for you to tell would be to jump into your `.asset-cache` folder and check there to see if the image has been 1.) Cached and 2.) Resized.  If it's been resized in the `.asset-cache` it's a bug in our proxy handlers, if it's not been resized at that point I would need to jump in and see if MiniMagick is misbehaving in a way that is contrary to what ImageMagick would do (but even then that would be murky water since AFAIW it simply just passes the values to ImageMagick command.)

**Comment by envygeeks** [comment]
Can you jump in and do a quick test like I described so I know where to start please?

**Comment by tohuw** [comment]
Ah, looks like the problem indeed goes away when I clear `.asset-cache`. It was not resized in the cache. Strange behavior; I'll run a few tests in an attempt to replicate it.

My current best guess is that cache must have been generated before I installed imagemagick on this particular system, and it never got replaced.

Sorry, should have connected these dots myself. Thanks for the help!
