### ISSUE TITLE
Assets not being created in _site

### ISSUE THREAD

**Issue by iamdriz** [jekyll/jekyll-assets#422]
I have the following in my `config.yml` file:
~~~
assets:
    liquid: true
    prefix: "/assets"
    integrity: false
    autowrite: true
    digest: true
    strict: false
    caching:
        enabled: false
        path: ".jekyll-cache/assets"
        type: file
    precompile: []
    cdn:
        baseurl: false
        prefix: false
    plugins:
    img:
        optim: {}
    compression:
        js:
            enabled: false
            opts: {}
        css:
            enabled: false
    sources:
        - _assets/css
        - _assets/img
        - _assets/js
~~~
And I have the gem installed and added into my `config.yml` as a plugin.
However when I call `jekyll build` I don't get an `assets` folder in my `_site`... and I don't get any errors... any ideas why?

**Comment by envygeeks** [comment]
I would have as much an idea as you without any proper source, a configuration file does little to help me do diagnostics as we tend to default safely to prevent user mistakes (except in the case of autowrite.)  Please provide an example repository (or your actual site if you can) so that it can be cloned and shimmed.  At that point I would have a clear idea of what's going on rather quickly.

You can also kick on `--verbose` which should ship a tonne of logs from Jekyll Assets and Sprockets, through Jekyll.  We do quite  bit of logging.

**Comment by iamdriz** [comment]
The Gemfile looks as:
~~~
source "https://rubygems.org"

gem "jekyll", "3.5.2"
gem 'kramdown'

group :jekyll_plugins do
    gem "jekyll-paginate"
    gem "jekyll-contentblocks"
    gem "jekyll-assets"
end
~~~

and my entire config.xml looks like:
~~~
permalink: /blog/:title.html
markdown: kramdown
plugins:
    - jekyll-paginate
    - jekyll-contentblocks
    - jekyll-assets
paginate: 10
paginate_path: /blog/:num

# Jekyll Assets
assets:
    liquid: true
    prefix: "/assets"
    integrity: false
    autowrite: true
    digest: true
    strict: false
    caching:
        enabled: false
        path: ".jekyll-cache/assets"
        type: file
    precompile: []
    cdn:
        baseurl: false
        prefix: false
    plugins:
    img:
        optim: {}
    compression:
        js:
            enabled: false
            opts: {}
        css:
            enabled: false
    sources:
        - _assets/css
        - _assets/js
        - _assets/img
~~~

**Comment by iamdriz** [comment]
Running on `Ruby 2.4.1`

**Comment by iamdriz** [comment]
I'm just setting up a repo for you as well... 2 secs.

**Comment by iamdriz** [comment]
Repo here: https://github.com/iamdriz/jekyll-sprockets

**Comment by envygeeks** [comment]
There are two things wrong:

1. You are using configuration from 3.x on 2.x (3.x is unreleased) please refer to to the 2.x documentation at https://github.com/jekyll/jekyll-assets/tree/2.4-legacy, some of your options will not work, as in 3.x we streamlined our configuration much more cleanly. Hopefully 3.x will be released next week, but now it's still being rewritten because we are running into some trouble with Sprockets and some features we expected that don't exactly exist that we have to create.
1. You are doing implicit assets on an explicit system.  Unlike Jekyll SASS, Jekyll Assets is an explicit system.  You either need to tell us to pre-compile the asset for you with the "assets" key, or you need to do `{% css mycss.css %}` to get it to compile.  We do seek out assets before we are asked to because that is a performance problem, we are much more complex than Jekyll because we are a pipeline, and doing implicit conversion is slow. 

Fix those problems and your assets should start to compile. Note: https://github.com/jekyll/jekyll-assets/tree/2.4-legacy#generating-css-with-jekyll-assets should help you more, skip over the non-relevant parts and it'll show you how our system works.

**Comment by iamdriz** [comment]
@envygeeks Ah okies... noticed you updated the README... so master branch is currently unusable?
I've switched my Gemfile to use `gem 'jekyll-sprockets', '2.4'`. However in order to get the assets to compile I had to add:
~~~
  assets:
    - "*"
~~~
to my `_config.xml` file... and doing: `{% css master.css %}` doesn't cause it compile or render the link into the html.. it just renders exactly that :/

**Comment by envygeeks** [comment]
What is "exactly that"?  If it renders the literally as in the `{% css %}` you are either using 3.x (which doesn't have `{% css %}` and only has `{% assets %}` or there I'll need more information, we do have that tag and it is actively used on my own site.
