### ISSUE TITLE
Asset tag can't handle variable as source

### ISSUE THREAD

**Issue by migueldemoura** [jekyll/jekyll-assets#430]
As mentioned in https://github.com/jekyll/jekyll-assets/issues/429#issuecomment-341943981, using the tag `asset` will throw an error when the src is a variable.

Example:
```
{% assign src = 'image.png' %}
{% asset '{{ src }}' %}
```

Exception:
```
Liquid Exception: couldn't find file '' Checked in thesepaths: [...]
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in `resolve!': couldn't find file '' (Sprockets::FileNotFound)
```

OS: Ubuntu 17.10
Jekyll: 3.6.2
Jekyll-Assets: current master - https://github.com/jekyll/jekyll-assets/commit/e8a8ba847e49a98f0b7c3b04c0f5b7ec05bccdb3

**Comment by envygeeks** [comment]
This issue has been specced out and is unverifiable.  Please provide a repository to replicate it.

**Comment by migueldemoura** [comment]
Will provide you with an MWE when #437's fixed.

**Comment by envygeeks** [comment]
This issue has been explicitly tested

https://github.com/jekyll/jekyll-assets/blob/f0dcdcb8a99075f0b2b268bc2488e4424e5ee34f/spec/fixture/utils/parse_liquid/assign.html#L1-L5

https://github.com/jekyll/jekyll-assets/blob/f0dcdcb8a99075f0b2b268bc2488e4424e5ee34f/spec/tests/lib/jekyll/assets/utils_spec.rb#L124-L139

Your example will need to provide more than an example unfortunately because we went out of our way to add in an example that matched your case to ensure this was an actual bug.

**Comment by migueldemoura** [comment]
Can't seem to reproduce it anymore. Will post here if I stumble upon it again. Thanks!
